# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Jonathan Scheibel"
description: > # this means to ignore newlines until "email:"
   Conheça alguns de meus estudos!

email: jsmorais@protonmail.com
#blog logo
logo: "/assets/images/21751965_10208171116114678_4956766131298360600_n.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Jonathan Scheibel'
author: 'Jonathan Scheibel'
author_image: "/assets/images/21751965_10208171116114678_4956766131298360600_n.jpg"

paginate: 5

url: "https://jonathanscheibel.github.io" # the base hostname & protocol for your site
baseurl: "https://jonathanscheibel.github.io"
#used to display twitter cards
twitter_handle: '@jonsmorais'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-108830795-1

# social icons and sharing options
social:
  - icon: twitter
    url: https://twitter.com/jonsmorais
    desc: Me siga no twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
#    'https://twitter.com/share?text=Criação+de+carteira+fria+e+integração+com+Telegram+%23[1%2F2]&url=https://jonathanscheibel.github.iohttps://jonathanscheibel.github.io/bitcoin/2024/04/01/criacao_btc_carteira_fria_telegram_part1'


#  - icon: facebook
#    url: https://www.facebook.com/ScheibelJonathan
#    desc: Perfil do facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon: github
    url: https://github.com/jonathanscheibel
    desc: Me siga no github
    share_url:
    share_title:
    share_link:


  - icon: linkedin
    url: https://www.linkedin.com/in/jonathansmorais
    desc: Qualificações gerais no LinkedIn
    share_url: https://www.linkedin.com/shareArticle
    share_title:
    share_link: "?mini=true&url="
#    'https://www.linkedin.com/shareArticle/?mini=true&url=https%3A%2F%2Fwww.tiagogouvea.com.br%2Fprofissional%2Fcomputador-programar-escolher%2F&title=Computador%20para%20programar.%20Qual%20o%20melhor%20e%20como%20escolher%3F%20-%20Tiago%20Gouvêa&summary=&source=AddToAny'
#    'https://www.linkedin.com/shareArticle?mini=true&url=https://blog.betrybe.com/tecnologia/aprenda-tudo-sobre-programacao/'
#    'https://www.linkedin.com/shareArticle?mini=true&url=https://jonathanscheibel.github.io/bitcoin/2024/04/01/criacao_btc_carteira_fria_telegram_part1
#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
